# =============================================================================
#  app/kpi_mapping.py
#  Source officielle : INDICATEURS_REVU.xlsx + MTFP_Collecte_Indicateurs_v5.xlsx
#  45 indicateurs MTFP 2016-2026 — ordre chronologique
# =============================================================================

KPI_META = {

    # ── GT1 — Gouvernance et Reformes (15 KPIs) ──
    'GT1PKI01': {
        'direction':          'SGM',
        'groupe':             'GT1',
        'url':                '/kpi/gt1pki01',
        'intitule':           'Taux de satisfaction des usagers du ministère',
        'definition':         'Niveau de satisfaction des usagers ayant eu recours aux services du MTFP',
        'objectif':           'Mesurer la perception et l’adhésion des citoyens ou usagers à la qualité des services publics offerts',
        'mode_calcul':        '(Nombre d\'usagers satisfaits / Nombre total d\'usagers répondants) × 100',
        'source':             'Rapports d\'enquêtes de satisfaction  des usagers',
        'unite':              '%',
        'formule_type':       'pourcentage',
        'numerateur_label':   'Nombre d\'usagers satisfaits',
        'denominateur_label': 'Nombre total d\'usagers repondants',
        'frequence':          'Annuelle',
    },
    'GT1PKI02': {
        'direction':          'SGM',
        'groupe':             'GT1',
        'url':                '/kpi/gt1pki02',
        'intitule':           'Taux de satisfaction des agents du ministère',
        'definition':         'Niveau de satisfaction des agents sur leurs conditions de travail et carrière',
        'objectif':           'Identifier les facteurs de mal-être et orienter la politique RH',
        'mode_calcul':        '(Nombre d\'agents satisfaits / Nombre total d\'agents répondants) × 100',
        'source':             'Rapports d\'enquêtes de satisfaction des agents',
        'unite':              '%',
        'formule_type':       'pourcentage',
        'numerateur_label':   'Nombre d\'agents satisfaits',
        'denominateur_label': 'Nombre total d\'agents repondants',
        'frequence':          'Annuelle',
    },
    'GT1PKI03': {
        'direction':          'DSI',
        'groupe':             'GT1',
        'url':                '/kpi/gt1pki03',
        'intitule':           'Taux de dématérialisation des services publics accessibles en ligne',
        'definition':         'Proportion des services du MTFP intégralement accessibles par voie numérique',
        'objectif':           'Mesurer l\'avancement de la dématérialisation et l\'accessibilité numérique',
        'mode_calcul':        'Nombre total de services publics en ligne / Nombre total de services publics identifiés) × 100',
        'source':             'Catalogue officiel du MTFP, portail de téléprocédures, rapports DSI, rapport annuel du Ministère du Numérique',
        'unite':              '%',
        'formule_type':       'pourcentage',
        'numerateur_label':   'Nombre de services publics en ligne',
        'denominateur_label': 'Nombre total de services publics identifies',
        'frequence':          'Annuelle',
    },
    'GT1PKI04': {
        'direction':          'DSI',
        'groupe':             'GT1',
        'url':                '/kpi/gt1pki04',
        'intitule':           'Taux d\'utilisation active des plateformes collaboratives internes',
        'definition':         'Proportion des directions utilisant effectivement les outils numériques (messagerie, SI, etc.)',
        'objectif':           'Évaluer le degré réel d\'appropriation des technologies au sein du ministère',
        'mode_calcul':        'Nombre d\'agents utilisant/nombre total d\'agents',
        'source':             'Journaux de connexion (logs DSI), enquête interne annuelle, rapports d\'audit des systèmes d\'information',
        'unite':              '%',
        'formule_type':       'pourcentage',
        'numerateur_label':   'Nombre d\'agents utilisant activement les outils',
        'denominateur_label': 'Nombre total de structures du ministere',
        'frequence':          'Annuelle',
    },
    'GT1PKI05': {
        'direction':          'DSI',
        'groupe':             'GT1',
        'url':                '/kpi/gt1pki05',
        'intitule':           'Taux de dématérialisation du courrier à la source',
        'definition':         'Part du courrier créé, transmis et archivé numériquement sans support papier',
        'objectif':           'Réduire les délais, les coûts et les risques de perte documentaire',
        'mode_calcul':        '(Nombre de courrier émis et reçus nativement numérique / Nombre total de courrier traité) x 100',
        'source':             'Système de gestion électronique des documents (GEC), registres du courrier, rapports de la DSI',
        'unite':              '%',
        'formule_type':       'pourcentage',
        'numerateur_label':   'Nombre de courriers dématérialisés à la source',
        'denominateur_label': 'Nombre total de courriers traites',
        'frequence':          'Annuelle',
    },
    'GT1PKI06': {
        'direction':          'DSI',
        'groupe':             'GT1',
        'url':                '/kpi/gt1pki06',
        'intitule':           'Pourcentage d\'actes administratifs authentifiés par signature électronique en avril 2026',
        'definition':         'Proportion des actes officiels signés par signature électronique qualifiée',
        'objectif':           'Accélérer les procédures et sécuriser les actes administratifs',
        'mode_calcul':        'Nombre d\'actes signés numériquement /sur nombre total d\'actes signés sur la période',
        'source':             'Système de signature électronique (DSI/Numérique), logs de la plateforme, rapports d\'audit interne',
        'unite':              '%',
        'formule_type':       'pourcentage',
        'numerateur_label':   'Nombre d\'actes signés électroniquement',
        'denominateur_label': 'Nombre total d\'actes administratifs produits',
        'frequence':          'Annuelle',
    },
    'GT1PKI07': {
        'direction':          'SGM',
        'groupe':             'GT1',
        'url':                '/kpi/gt1pki07',
        'intitule':           'Taux de mise en œuvre  des recommandations issues des missions d\'audit et d\'inspection',
        'definition':         'la proportion des recommandations formulées à l\'issue des missions d\'audit et d\'inspection qui ont été effectivement appliquées par les entités auditées, dans un délai donné',
        'objectif':           'Encourager les entités auditées à corriger leurs dysfonctionnements et à renforcer leurs systèmes internes',
        'mode_calcul':        'Taux de mise en œuvre=( Nombre de recommandations effectivement mises en œuvre​/Nombre total de recommandations formulées ) x 100',
        'source':             'Documents produits par l\'organe d\'audit/inspection pour tracer l\'état d\'avancement',
        'unite':              '%',
        'formule_type':       'pourcentage',
        'numerateur_label':   'Recommandations mises en œuvre',
        'denominateur_label': 'Nombre total de recommandations emises',
        'frequence':          'Annuelle',
    },
    'GT1PKI08': {
        'direction':          'SGM',
        'groupe':             'GT1',
        'url':                '/kpi/gt1pki08',
        'intitule':           'Taux de couverture des ministères en missions d\'audit et d\'inspection',
        'definition':         'Proportion des institutions publiques ayant fait l\'objet d\'au moins un audit ou inspection',
        'objectif':           'Garantir la redevabilité et prévenir les irrégularités de gestion',
        'mode_calcul':        '(Nombre de ministères ayant reçu au moins une mission d\'audit ou d\'inspection dans la période / Nombre total de ministères  dans le périmètre) × 100',
        'source':             'Rapports de l\'Inspection Générale du MTFP, programme annuel d\'audit, rapports des corps d\'inspection',
        'unite':              '%',
        'formule_type':       'pourcentage',
        'numerateur_label':   'Nombre de ministères audités',
        'denominateur_label': 'Nombre total de ministeres a auditer',
        'frequence':          'Annuelle',
    },
    'GT1PKI09': {
        'direction':          'DSI',
        'groupe':             'GT1',
        'url':                '/kpi/gt1pki09',
        'intitule':           'Taux de couverture des structures du Ministère  en  connectivité',
        'definition':         'Proportion des structures disposant d\'une connexion  opérationnelle',
        'objectif':           'Garantir l\'accès aux outils et réduire la fracture numérique interne',
        'mode_calcul':        '(Nombre de structures disposant d\'une connectivité opérationnelle  / Nombre total de structures du MTFP) × 100',
        'source':             'Inventaire réseau DSI, rapports de monitoring réseau, rapports des DDTFP sur l\'état des équipements',
        'unite':              '%',
        'formule_type':       'pourcentage',
        'numerateur_label':   'Nombre de structures connectées',
        'denominateur_label': 'Nombre total de structures du ministere',
        'frequence':          'Annuelle',
    },
    'GT1PKI10': {
        'direction':          'SGM',
        'groupe':             'GT1',
        'url':                '/kpi/gt1pki10',
        'intitule':           'Taux de traitement des plaintes des usagers',
        'definition':         'Part des plaintes traitées efficacement dans un délai maximal de 30 jours',
        'objectif':           'Garantir le droit de recours et renforcer la confiance des citoyens',
        'mode_calcul':        '(Nombre de Plaintes traitées dans un délai ≤ 30 jours / Nombre total de plaintes reçues sur la période) × 100',
        'source':             'Registre des plaintes (central/déconcentré), ticketing CCSP/GSRU, rapport Service Relations Usagers (SRU)',
        'unite':              '%',
        'formule_type':       'pourcentage',
        'numerateur_label':   'Plaintes traitées ≤30 jours',
        'denominateur_label': 'Nombre total de plaintes enregistrees',
        'frequence':          'Annuelle',
    },
    'GT1PKI11': {
        'direction':          'SGM',
        'groupe':             'GT1',
        'url':                '/kpi/gt1pki11',
        'intitule':           'Taux  de couverture des communes en CCSP / GSRU',
        'definition':         'Proportion des communes disposant d\'un centre de services publics opérationnel',
        'objectif':           'Mesurer la déconcentration physique des services publics numériques',
        'mode_calcul':        '(Nombre de communes disposant d\'au moins un CCSP ou GSRU opérationnel / 77 communes) × 100',
        'source':             'Tableau de bord CCSP (DSI), rapports projet PARMAP, rapports supervision DSI, données ANCB',
        'unite':              '%',
        'formule_type':       'pourcentage',
        'numerateur_label':   'Communes avec au moins un CCSP ou GSRU opérationnel',
        'denominateur_label': 'Nombre total de communes du Benin',
        'frequence':          'Annuelle',
    },
    'GT1PKI12': {
        'direction':          'DPAF',
        'groupe':             'GT1',
        'url':                '/kpi/gt1pki12',
        'intitule':           'Taux d\'accroissement moyen des dotations budgétaires allouées au Ministère de 2016-2026',
        'definition':         'Mesure l\'évolution annuelle moyenne, en pourcentage, des crédits budgétaires alloués au Ministère du Travail et de la Fonction Publique (MTFP) sur la période 2016-2026, calculée comme le taux de croissance annuel composé (TCAC) entre la dotation de l\'année de référence (2016) et la dotation de l\'année terminale (2026)',
        'objectif':           'Évaluer l\'engagement progressif de l\'État en faveur du MTFP, apprécier la cohérence entre les priorités affichées dans le PAG et les ressources effectivement allouées, et orienter les arbitrages budgétaires futurs',
        'mode_calcul':        'Taux d’accroissement moyen = [((Dotation_2026)/(Dotation_2016 ))^(1/10)-1] Remarque : on utilise la moyenne géométrique (taux de croissance annuel composé) car elle est plus représentative d’une évolution pluriannuelle qu’une moyenne arithmétique des taux annuels',
        'source':             '- Lois de finances initiales et rectificatives (2016-2026)                  -MEF — Documents de programmation pluriannuelle des dépenses (DPPD) du MTFP — Rapports annuels de performance (RAP) du MTFP — Direction de la Planification, de l\'Administration et des Finances (DPAF/MTFP)',
        'unite':              '%',
        'formule_type':       'pourcentage',
        'numerateur_label':   '',
        'denominateur_label': 'Dotation budgetaire de reference (2016)',
        'frequence':          'Annuelle',
    },
    'GT1PKI13': {
        'direction':          'DPAF',
        'groupe':             'GT1',
        'url':                '/kpi/gt1pki13',
        'intitule':           'Taux moyen d\'exécution financière des dotations budgétaires du Ministère de 2016-2026',
        'definition':         'Mesure la proportion moyenne des crédits budgétaires alloués au MTFP qui ont effectivement été engagés et ordonnancés (ou payés) sur la période 2016-2026, par rapport aux dotations inscrites en loi de finances',
        'objectif':           'Évaluer la capacité d\'absorption budgétaire du MTFP, identifier les causes de sous-consommation des crédits et orienter les mesures de renforcement des capacités de gestion financière et de planification',
        'mode_calcul':        'Pour chaque année n : Pourcentage d\'exécution financière = ( Dépenses réalisées [engagements ou paiements] / Dotations budgétaires inscrites) × 100 Pourcentage moyen 2016-2026 = Moyenne arithmétique des taux annuels sur la période',
        'source':             '— Comptes de gestion et rapports d\'exécution budgétaire annuels (MEF) — Rapports annuels de performance (RAP) du MTFP — Rapports de la DPAF/MTFP sur l\'exécution budgétaire',
        'unite':              '%',
        'formule_type':       'pourcentage',
        'numerateur_label':   'Taux moyen d\'exécution financière des d',
        'denominateur_label': 'Dotation budgetaire allouee',
        'frequence':          'Annuelle',
    },
    'GT1PKI14': {
        'direction':          'DPAF',
        'groupe':             'GT1',
        'url':                '/kpi/gt1pki14',
        'intitule':           'Taux moyen d\'exécution physique des activités du PTA de 2016-2026',
        'definition':         'Proportion moyenne des activités inscrites dans le Plan de Travail Annuel (PTA) du MTFP qui ont été effectivement réalisées (en totalité ou partiellement, selon un seuil de réalisation défini) au cours de la période 2016-2026, exprimée en pourcentage du nombre total d\'activités programmées',
        'objectif':           'Apprécier la performance opérationnelle du MTFP dans la mise en œuvre de ses programmes et activités, identifier les écarts entre programmation et réalisation, et orienter les décisions correctives en matière de planification et de gestion',
        'mode_calcul':        'Pour chaque année n :Pourcentage d\'exécution physique = (Nombre d\'activités réalisées / Nombre total d\'activités programmées au PTA) × 100 Pourcentage moyen 2016-2026 = Moyenne arithmétique des taux annuels sur la période NB : Une activité est considérée « réalisée » si son  pourcentage de réalisation physique est ≥ 80 %',
        'source':             '— Plans de Travail Annuels (PTA) du MTFP — Rapports annuels de performance (RAP) du MTFP — Rapports de suivi trimestriel des activités (DPAF/MTFP) — Rapports d\'évaluation à mi-parcours des programmes',
        'unite':              '%',
        'formule_type':       'pourcentage',
        'numerateur_label':   'Taux moyen d\'exécution physique des act',
        'denominateur_label': 'Nombre total d\'activites prevues au PTA',
        'frequence':          'Annuelle',
    },
    'GT1PKI15': {
        'direction':          'DPAF',
        'groupe':             'GT1',
        'url':                '/kpi/gt1pki15',
        'intitule':           'Ratio d\'efficience sur la période de 2016-2026',
        'definition':         'Rapport entre le pourcentage moyen d\'exécution physique des activités (résultats obtenus) et le pourcentage moyen d\'exécution financière des dotations budgétaires (ressources consommées) du MTFP sur la période 2016-2026. Un ratio supérieur à 1 indique une efficience favorable : les réalisations physiques sont proportionnellement supérieures à la consommation des ressources financières',
        'objectif':           'Mesurer la capacité du MTFP à produire des résultats tangibles proportionnellement aux ressources financières mobilisées, permettant d\'évaluer l\'efficience de la dépense publique et d\'identifier les gains de productivité réalisés ou à réaliser',
        'mode_calcul':        'Ratio d\'efficience = Taux moyen d\'exécution physique (%) /Taux moyen d\'exécution financière (%) Interprétation : — Ratio > 1 : efficience positive (plus de réalisations physiques que de ressources consommées proportionnellement) — Ratio = 1 : neutralité (équilibre entre réalisations et ressources) — Ratio < 1 : sous-efficience (ressources consommées supérieures aux réalisations physiques)',
        'source':             'Rapports annuels de performance (RAP) du MTFP — Rapports d\'exécution budgétaire (DPAF/MTFP et MEF) — Plans de Travail Annuels (PTA) et bilans d\'activités',
        'unite':              '%',
        'formule_type':       'indice',
        'numerateur_label':   'Ratio d\'efficience sur la période de 20',
        'denominateur_label': 'Ressources budgetaires engagees',
        'frequence':          'Annuelle',
    },
    # ── GT2 — Travail et Securite Sociale (9 KPIs) ──
    'GT2PKI01': {
        'direction':          'DGT',
        'groupe':             'GT2',
        'url':                '/kpi/gt2pki01',
        'intitule':           'Taux d\'efficacité des interventions de retrait des enfants en situation de PFTE',
        'definition':         'Permet de comparer les enfants retirés par rapport aux cas détectés ou signalés',
        'objectif':           'Mesurer l\'efficacité des interventions de protection de l\'enfant',
        'mode_calcul':        'Nombre d\'enfants retirés/Nombre de cas détectés ou signalés',
        'source':             'Rapports de l\'Inspection du Travail (ITB), du CNLTE, des ONG (UNICEF, etc.) et du Ministère des Affaires Sociales',
        'unite':              '%',
        'formule_type':       'pourcentage',
        'numerateur_label':   'Nombre d\'enfants retirés',
        'denominateur_label': 'Nombre d\'enfants identifies en PFTE',
        'frequence':          'Annuelle',
    },
    'GT2PKI02': {
        'direction':          'DGT',
        'groupe':             'GT2',
        'url':                '/kpi/gt2pki02',
        'intitule':           'Taux d\'efficacité post retrait des enfants en situation de PFTE (Pourcentage d\'enfants réinsérés)',
        'definition':         'Met l\'accent sur le suivi post retrait',
        'objectif':           'Mesurer l\'efficacité intégrée des interventions de l\'État (MTFP, partenaires) en matière de protection et de réinsertion durable des enfants victimes de travail, au-delà du simple retrait physique. Évaluer la qualité du suivi post-retrait et l\'impact social des programmes',
        'mode_calcul':        'Nombre d\'enfants réinsérés/Nombre d\'enfants retirés',
        'source':             '— Rapports annuels de l\'Inspection du Travail du Bénin (ITB) — Rapports du Comité National de Lutte contre le Travail des Enfants (CNLTE) — Données des ONG partenaires (UNICEF, Plan International,) — Ministère des Affaires Sociales — base de données des enfants pris en charge — Rapports de suivi post-retrait des structures de protection de l\'enfance',
        'unite':              '%',
        'formule_type':       'pourcentage',
        'numerateur_label':   'Nombre d\'enfants réinsérés',
        'denominateur_label': 'Nombre total d\'enfants retires',
        'frequence':          'Annuelle',
    },
    'GT2PKI04': {
        'direction':          'DGT',
        'groupe':             'GT2',
        'url':                '/kpi/gt2pki04',
        'intitule':           'Pourcentage d\'assurés percevant les prestations  de la CNSS par des moyens électroniques et par virement bancaire',
        'definition':         'Part des assurés CNSS recevant leurs prestations via banque ou mobile money',
        'objectif':           'Moderniser le paiement, améliorer la sécurité et la traçabilité',
        'mode_calcul':        '(Nombre d\'assurés recevant leurs prestations par virement bancaire ou moyen électronique / Nombre total d\'assurés percevant des prestations) × 100',
        'source':             'Base de gestion des assurés CNSS, rapports financiers et statistiques, rapports de la Direction du Recouvrement',
        'unite':              '%',
        'formule_type':       'pourcentage',
        'numerateur_label':   'Assurés payés électroniquement',
        'denominateur_label': 'Nombre total d\'assures CNSS',
        'frequence':          'Annuelle',
    },
    'GT2PKI05': {
        'direction':          'DGT',
        'groupe':             'GT2',
        'url':                '/kpi/gt2pki05',
        'intitule':           'Délai moyen de liquidation des pensions à la CNSS',
        'definition':         'Durée entre le dépôt du dossier complet et le premier versement',
        'objectif':           'Garantir aux assurés une transition financière rapide',
        'mode_calcul':        '∑(Date de demande - Date de signature)/ Nombre de dossiers liquidés',
        'source':             'Système de gestion de la CNSS, rapports de la Direction des Prestations, audits de performance',
        'unite':              'jours',
        'formule_type':       'moyenne',
        'numerateur_label':   '',
        'denominateur_label': 'Nombre de dossiers de pension traites',
        'frequence':          'Annuelle',
    },
    'GT2PKI06': {
        'direction':          'DGT',
        'groupe':             'GT2',
        'url':                '/kpi/gt2pki06',
        'intitule':           'Taux de conflictualité dans le secteur public',
        'definition':         'Proportion des entités (ministères, institutions, établissements et organismes publics) du secteur public béninois ayant connu au moins un conflit collectif du travail déclaré (grève, arrêt de travail, mouvement de protestation collective avec préavis) sur une période de référence donnée, rapportée au nombre total d\'entités du secteur public',
        'objectif':           'Évaluer l\'intensité des tensions sociales dans le secteur public, mesurer l\'impact des politiques de dialogue social et de prévention des conflits menées par le MTFP, et orienter les interventions de la DGT',
        'mode_calcul':        'Taux  de conflictualité dans le secteur public = (Nombre d\'entités du secteur public ayant enregistré au moins un conflit collectif déclaré / Nombre total d\'entités du secteur public) × 100 NB : Un conflit collectif est « déclaré » lorsqu\'un préavis de grève ou un procès-verbal de constat de différend collectif a été déposé auprès de la DGT',
        'source':             '- Registre des préavis de grève et des conflits collectifs                   — DGT — Rapports annuels de la Direction des Relations Professionnelles et du Dialogue Social (MTFP) — Direction Générale du Travail — statistiques des conflits collectifs — Rapports des partenaires sociaux (organisations syndicales, organisations patronales) )',
        'unite':              '%',
        'formule_type':       'pourcentage',
        'numerateur_label':   'Nombre de conflits dans le secteur public',
        'denominateur_label': 'Nombre de relations de travail dans le secteur public',
        'frequence':          'Annuelle',
    },
    'GT2PKI07': {
        'direction':          'DGT',
        'groupe':             'GT2',
        'url':                '/kpi/gt2pki07',
        'intitule':           'Taux de conflictualité dans le secteur privé',
        'definition':         'Proportion des entreprises du secteur privé formel enregistrées au Bénin ayant connu au moins un conflit collectif du travail déclaré (grève, lock-out, arrêt collectif de travail avec préavis) sur une période de référence, rapportée au nombre total d\'entreprises du secteur privé formel enregistrées',
        'objectif':           'Évaluer le climat social dans les entreprises du secteur privé béninois, mesurer l\'efficacité des mécanismes de dialogue social et de prévention des conflits encadrés par le MTFP, et orienter les programmes de sensibilisation des employeurs et des travailleurs',
        'mode_calcul':        'Taux de conflictualité dans le secteur privé = (Nombre d\'entreprises du secteur privé formel ayant enregistré au moins un conflit collectif déclaré / Nombre total d\'entreprises du secteur privé formel enregistrées) × 100',
        'source':             '— Registre des préavis de grève et des conflits collectifs — DGT — Rapports annuels de la Direction des Relations Professionnelles et du Dialogue Social (MTFP) — Données du RCCM (Registre du Commerce) pour le dénominateur — Rapports des partenaires sociaux du secteur privé (Syndicats sectoriels)',
        'unite':              '%',
        'formule_type':       'pourcentage',
        'numerateur_label':   'Nombre de conflits dans le secteur privé',
        'denominateur_label': 'Nombre de relations de travail dans le secteur prive',
        'frequence':          'Annuelle',
    },
    'GT2PKI08': {
        'direction':          'DGT',
        'groupe':             'GT2',
        'url':                '/kpi/gt2pki08',
        'intitule':           'Taux de représentativité des organisations ou conférations syndicales',
        'definition':         'Proportion des travailleurs (salariés du secteur public et du secteur privé formel) adhérant à une organisation syndicale reconnue ou affiliée à une confédération syndicale représentative au Bénin, rapportée à l\'ensemble de la population salariée concernée. Cet indicateur mesure également la représentativité institutionnelle, c\'est-à-dire le nombre d\'organisations syndicales ou de confédérations ayant satisfait aux critères légaux de représentativité reconnus par le MTFP',
        'objectif':           'Évaluer la vitalité du mouvement syndical béninois, mesurer le degré d\'organisation des travailleurs et la capacité des partenaires sociaux à représenter effectivement les intérêts des salariés dans le cadre du dialogue social et de la négociation collective',
        'mode_calcul':        'Taux de syndicalisation = (Nombre de travailleurs adhérant à une organisation syndicale représentative / Nombre total de travailleurs salariés du secteur formel) × 100 Taux de représentativité institutionnelle = (Nombre d\'organisations syndicales satisfaisant aux critères légaux de représentativité / Nombre total d\'organisations syndicales déclarées) × 100',
        'source':             'Répertoire des organisations syndicales et confédérations — MTFP/DGT — Résultats des élections professionnelles dans les entreprises et la fonction publique — Rapports de la Direction des Relations Professionnelles et du Dialogue Social — Données de l\'OIT sur la syndicalisation au Bénin',
        'unite':              '%',
        'formule_type':       'pourcentage',
        'numerateur_label':   '',
        'denominateur_label': 'Nombre total d\'agents / electeurs inscrits',
        'frequence':          'Annuelle',
    },
    'GT2PKI09': {
        'direction':          'DGT',
        'groupe':             'GT2',
        'url':                '/kpi/gt2pki09',
        'intitule':           'Taux de succès des médiations de l\'Inspection du Travail',
        'definition':         'Proportion des conflits individuels et collectifs du travail (litiges entre employeurs et travailleurs ou entre organisations syndicales et employeurs) portés devant les services de l\'Inspection du Travail du Bénin (ITB) qui ont été réglés à l\'amiable à l\'issue de la procédure de conciliation, sans nécessiter de recours judiciaire',
        'objectif':           'Évaluer l\'efficacité de la fonction de conciliation de l\'Inspection du Travail dans la prévention et la résolution des conflits du travail, mesurer la contribution de l\'ITB à la paix sociale et orienter le renforcement des capacités des inspecteurs en matière de médiation',
        'mode_calcul':        'Nombre de conflit réglés/Nombre de conflit enrégistrés',
        'source':             'Registres de conciliation des services de l\'Inspection du Travail du Bénin (ITB) — Rapports annuels de la Direction Générale du Travail (DGT/MTFP) — Statistiques du travail — Département des Normes et de la Statistique du Travail — Rapports des Inspections Régionales du Travail',
        'unite':              '%',
        'formule_type':       'pourcentage',
        'numerateur_label':   'Médiations réussies',
        'denominateur_label': 'Nombre total de mediations engagees',
        'frequence':          'Annuelle',
    },
    'GT2PKI10': {
        'direction':          'DGT',
        'groupe':             'GT2',
        'url':                '/kpi/gt2pki10',
        'intitule':           'Taux de conformité aux normes de sécurité (SST)',
        'definition':         'Proportion des entreprises contrôlées respectant les normes de santé/sécurité',
        'objectif':           'Mesurer l\'effectivité de la réglementation du travail en entreprise',
        'mode_calcul':        '(Nombre d\'entreprises conformes aux normes / Nombre Total d\'entreprises contrôlées) × 100',
        'source':             'Rapports de mission des inspecteurs (ITB), procès-verbaux de contrôle, base de données des contrôles SST',
        'unite':              '%',
        'formule_type':       'pourcentage',
        'numerateur_label':   'Établissements conformes aux normes SST',
        'denominateur_label': 'Nombre d\'etablissements controles',
        'frequence':          'Annuelle',
    },
    # ── GT3 — Fonction Publique (21 KPIs) ──
    'GT3PKI01': {
        'direction':          'DSI',
        'groupe':             'GT3',
        'url':                '/kpi/gt3pki01',
        'intitule':           'Taux de numérisation des archives des personnels de l\'État',
        'definition':         'Proportion des dossiers individuels d\'agents numérisés dans le SIGRH',
        'objectif':           'Sécuriser les dossiers et faciliter la gestion des carrières',
        'mode_calcul':        'Nombre de dossiers complets d\'agents disponible numériquement/Nombre total d\'agents',
        'source':             'Base de données SIGRH, rapports de la Direction de l\'Archivage, rapports d\'audit du SIGRH',
        'unite':              '%',
        'formule_type':       'pourcentage',
        'numerateur_label':   'Dossiers numérisés',
        'denominateur_label': 'Nombre total de dossiers physiques a numeriser',
        'frequence':          'Annuelle',
    },
    'GT3PKI02': {
        'direction':          'DGFP',
        'groupe':             'GT3',
        'url':                '/kpi/gt3pki02',
        'intitule':           'Délai  moyen de parution des actes de carrière des agents de l\'Etat',
        'definition':         'Durée entre la soumission d\'un dossier et la publication de l\'acte officiel',
        'objectif':           'Réduire les retards et sécuriser les droits des agents',
        'mode_calcul':        '∑(Date de signature - Date de demande)/ Nombre total d\'actes traités',
        'source':             'SI de gestion des actes (MTFP), Journal Officiel, rapports de la DGRH sur le traitement des dossiers',
        'unite':              'jours',
        'formule_type':       'moyenne',
        'numerateur_label':   '',
        'denominateur_label': 'Nombre d\'actes de carriere traites',
        'frequence':          'Annuelle',
    },
    'GT3PKI03': {
        'direction':          'DGFP',
        'groupe':             'GT3',
        'url':                '/kpi/gt3pki03',
        'intitule':           'Pourcentage de renouvellement du personnel dans la Fonction Publique ( Turn-Over)',
        'definition':         'Proportion des agents de la Fonction Publique béninoise ayant quitté leur poste (départs toutes causes confondues : retraite, décès, démission, fin de contrat, révocation, mise en disponibilité, détachement définitif) sur une période de référence, rapportée à l\'effectif total moyen de la Fonction Publique sur la même période',
        'objectif':           'Mesurer la stabilité et le renouvellement des effectifs de la Fonction Publique béninoise, évaluer les besoins en recrutement de remplacement, anticiper les déséquilibres d\'effectifs sectoriels et orienter la politique de gestion prévisionnelle des emplois et des compétences (GPEC) de l\'État',
        'mode_calcul':        'Pourcentage de de rotation du personnel dans la Fonction Publique = (Nombre total de départs / Effectif moyen de la FP sur l\'année) × 100 NB : Les mutations internes entre ministères ne sont pas comptabilisées comme des départs',
        'source':             '— Direction Générale de la Fonction Publique (DGFP) — fichier des mouvements d\'agents — Base de données du Système d\'Information de Gestion des Ressources Humaines (SIGRH) — Rapports annuels de la DGFP sur les effectifs et les mouvements de personnel — Direction des Retraites et des Archives (DGFP) — statistiques des départs à la retraite — Rapport annuel de la DGRH sur la gestion des carrières',
        'unite':              '%',
        'formule_type':       'pourcentage',
        'numerateur_label':   'Agents ayant quitté la FP dans l\'année',
        'denominateur_label': 'Effectif total moyen de la Fonction Publique',
        'frequence':          'Annuelle',
    },
    'GT3PKI04': {
        'direction':          'DGFP',
        'groupe':             'GT3',
        'url':                '/kpi/gt3pki04',
        'intitule':           'Pourcentage de procès gagnés par l\'État en matière de contentieux de la Fonction Publique',
        'definition':         'Part des affaires de fonction publique où l\'État obtient gain de cause',
        'objectif':           'Évaluer la défense juridique de l\'État et prévenir le contentieux',
        'mode_calcul':        '(Nombre de procès gagnés / Nombre Total de procès jugés en FP) × 100',
        'source':             'Greffe de la Cour Suprême, Direction des Affaires Juridiques, rapports du Secrétariat Général (MTFP)',
        'unite':              '%',
        'formule_type':       'pourcentage',
        'numerateur_label':   'Procès gagnés par l\'État',
        'denominateur_label': 'Nombre total de proces engages par l\'Etat',
        'frequence':          'Annuelle',
    },
    'GT3PKI05': {
        'direction':          'DGFP',
        'groupe':             'GT3',
        'url':                '/kpi/gt3pki05',
        'intitule':           'Délai moyen de la procédure disciplinaire par instance disciplinaire',
        'definition':         'Durée entre le déclenchement de la procédure et la décision définitive',
        'objectif':           'Garantir une procédure équitable et renforcer l\'éthique',
        'mode_calcul':        '∑(Date de déclenchement de la procédure - Date de fin de la procédure) / Nombre de procédures traitées',
        'source':             'Registres des instances (Conseil de Discipline, CAP), Direction des Affaires Juridiques, rapports DGRH',
        'unite':              'jours',
        'formule_type':       'moyenne',
        'numerateur_label':   '',
        'denominateur_label': 'Nombre de procedures disciplinaires traitees',
        'frequence':          'Annuelle',
    },
    'GT3PKI06': {
        'direction':          'DGFP',
        'groupe':             'GT3',
        'url':                '/kpi/gt3pki06',
        'intitule':           'Délai moyen de proclamation des résultats des concours des agents de l\'Etat',
        'definition':         'Temps moyen, exprimé en jours calendaires, séparant la fin des épreuves d’un concours et la proclamation officielle des résultats',
        'objectif':           'Evalue la célérité administrative et la transparence envers les candidats',
        'mode_calcul':        '∑(Date de proclamation officielle des résultats – Date de fin des épreuves) / Nombre total de concours',
        'source':             'PV de délibération, Communiqué du concours,   compte rendu des opérations du concours, formulaire de requête d’extraction des données du SYGECO',
        'unite':              'jours',
        'formule_type':       'moyenne',
        'numerateur_label':   '',
        'denominateur_label': 'Nombre de concours organises',
        'frequence':          'Annuelle',
    },
    'GT3PKI07': {
        'direction':          'DGFP',
        'groupe':             'GT3',
        'url':                '/kpi/gt3pki07',
        'intitule':           'Délai moyen de liquidation et de remise des livrets de pension aux agents de l\'Etat admis à la retraite relevant du (FNRB)',
        'definition':         'Délai entre l\'admission à la retraite et la remise effective du livret',
        'objectif':           'Garantir une transition financière rapide aux retraités de l\'État',
        'mode_calcul':        'Délai =∑(Date de remise du livret – Date d\'admission à la retraite) / Nombre total de livrets remis',
        'source':             'Base de données FNRB, rapports trimestriels FNRB, registre de la Direction de la Fonction Publique',
        'unite':              'jours',
        'formule_type':       'moyenne',
        'numerateur_label':   '',
        'denominateur_label': 'Nombre de dossiers de pension traites (FNRB)',
        'frequence':          'Annuelle',
    },
    'GT3PKI08': {
        'direction':          'DGFP',
        'groupe':             'GT3',
        'url':                '/kpi/gt3pki08',
        'intitule':           'Nombre de pièces constitutives du dossier de retraite et de pension des agents de l\'Etat',
        'definition':         'Nombre de documents requis par le FNRB pour liquider une pension',
        'objectif':           'Mesurer la simplification administrative du dossier de retraite',
        'mode_calcul':        'Décompte direct du nombre de pièces listées dans le guide officiel de constitution du dossier de retraite, en vigueur à la date de référence',
        'source':             'Guide officiel de constitution du dossier (FNRB/MTFP), circulaires, rapports de simplification',
        'unite':              'nombre',
        'formule_type':       'nombre',
        'numerateur_label':   '',
        'denominateur_label': '',
        'frequence':          'Annuelle',
    },
    'GT3PKI09': {
        'direction':          'DGFP',
        'groupe':             'GT3',
        'url':                '/kpi/gt3pki09',
        'intitule':           'Délai de notification des actes d\'admission à la retraite aux agents de l\'Etat',
        'definition':         'Délai entre la date de départ et la notification officielle de l\'acte',
        'objectif':           'Permettre aux agents de préparer sereinement leur transition',
        'mode_calcul':        'Délai = ∑(Date de notification - Date de signature de l\'acte)/ Nombre d\'agents concernés',
        'source':             'Registre de la Direction de la Fonction Publique, base SIGRH, rapports du FNRB',
        'unite':              'jours',
        'formule_type':       'moyenne',
        'numerateur_label':   '',
        'denominateur_label': 'Nombre d\'actes d\'admission a la retraite traites',
        'frequence':          'Annuelle',
    },
    'GT3PKI10': {
        'direction':          'DGFP',
        'groupe':             'GT3',
        'url':                '/kpi/gt3pki10',
        'intitule':           'Pourcentage d\'agents publics ayant souscrit au formulaire du Code d\'éthique et des valeurs de l\'administration publique',
        'definition':         'Proportion d\'agents actifs ayant formellement adhéré au code',
        'objectif':           'Promouvoir l\'intégrité et la neutralité dans l\'administration',
        'mode_calcul':        '(Nombre d\'agents ayant signé/validé le formulaire d\'adhésion au Code d\'Éthique / Nombre total d\'agents de l\'État en activité) × 100',
        'source':             'Base des signatures (DGRH), rapports de la Direction de la Déontologie, SIGRH',
        'unite':              '%',
        'formule_type':       'pourcentage',
        'numerateur_label':   'Agents ayant signé le Code d\'éthique',
        'denominateur_label': 'Nombre total d\'agents publics',
        'frequence':          'Annuelle',
    },
    'GT3PKI11': {
        'direction':          'DGFP',
        'groupe':             'GT3',
        'url':                '/kpi/gt3pki11',
        'intitule':           'Nombre d\'agents recrutés dans l\'Administration  publique sur la période de 2016 à 2026',
        'definition':         'Nombre cumulatif d\'agents recrutés dans l\'administration',
        'objectif':           'Évaluer la capacité de renouvellement des effectifs de l\'État',
        'mode_calcul':        'Décompte cumulatif des actes de recrutement (arrêtés de nomination, décrets de titularisation, contrats d\'engagement) validés sur les deux périodes de référence : 2006 à 2016 et 20116 à 2026',
        'source':             'Fichier des recrutements (DGRH), Journal Officiel, rapports annuels DGRH, base SIGRH',
        'unite':              'nombre',
        'formule_type':       'nombre',
        'numerateur_label':   '',
        'denominateur_label': '',
        'frequence':          'Annuelle',
    },
    'GT3PKI12': {
        'direction':          'DGFP',
        'groupe':             'GT3',
        'url':                '/kpi/gt3pki12',
        'intitule':           'Délai moyen de mise à disposition des ministères des agents nouvellement recrutés',
        'definition':         'Délai entre les résultats du concours et la prise de service',
        'objectif':           'Réduire la période d\'inactivité post-recrutement',
        'mode_calcul':        'Délai  = ∑(Date de mise à disposition - Date de proclamation des résultats )/ Nombre  total de concours',
        'source':             'Registre des affectations (DGRH), registres de présence ministériels, rapports de déploiement',
        'unite':              'jours',
        'formule_type':       'moyenne',
        'numerateur_label':   '',
        'denominateur_label': 'Nombre d\'agents nouvellement recrutes mis a disposition',
        'frequence':          'Annuelle',
    },
    'GT3PKI13': {
        'direction':          'DGFP',
        'groupe':             'GT3',
        'url':                '/kpi/gt3pki13',
        'intitule':           'Pourcentage des agents nouvellement recrutés ayant souscrit au formulaire du code d\'éthique et des valeurs de l\'Administration Publique',
        'definition':         'Proportion d\'agents recrutés ayant signé le code à leur intégration',
        'objectif':           'Inculquer les valeurs de service public dès l\'entrée en fonction',
        'mode_calcul':        '(Nombre de nouveaux recrutés ayant signé/validé le formulaire du Code d\'Éthique lors de leur intégration / Nombre total de nouveaux recrutés sur la période) × 100',
        'source':             'Base des signatures DGRH (nouveaux recrutés), rapports de formation initiale, SIGRH',
        'unite':              '%',
        'formule_type':       'pourcentage',
        'numerateur_label':   'Nouveaux recrutés ayant signé le Code d\'éthique',
        'denominateur_label': 'Nombre total d\'agents nouvellement recrutes',
        'frequence':          'Annuelle',
    },
    'GT3PKI14': {
        'direction':          'DGFP',
        'groupe':             'GT3',
        'url':                '/kpi/gt3pki14',
        'intitule':           'Nombre d\'agents recrutés dans la fonction publique par secteur sur la période 2016-2026',
        'definition':         'Décompte des recrutements ventilé par ministère',
        'objectif':           'Analyser la cohérence entre recrutements et besoins sectoriels',
        'mode_calcul':        'Décompte cumulatif des actes de recrutement par secteur ministériel',
        'source':             'Fichier national des recrutements (DGRH), rapports sectoriels, module effectifs du SIGRH',
        'unite':              'nombre',
        'formule_type':       'nombre',
        'numerateur_label':   '',
        'denominateur_label': '',
        'frequence':          'Annuelle',
    },
    'GT3PKI15': {
        'direction':          'DGFP',
        'groupe':             'GT3',
        'url':                '/kpi/gt3pki15',
        'intitule':           'Taux de conformité au quota de représentativité des personnes handicapées dans les recrutements de la fonction publique',
        'definition':         'Nombre cumulatif de PSH recrutées selon les quotas légaux',
        'objectif':           'Évaluer le respect des engagements d\'inclusion',
        'mode_calcul':        'Nombre de concours ayant respectés le quota/Nombre de concours total',
        'source':             'Registre DGRH, suivi des quotas (Affaires Sociales), rapports des Commissions d\'Accès',
        'unite':              '%',
        'formule_type':       'pourcentage',
        'numerateur_label':   'Recrutements respectant le quota PSH',
        'denominateur_label': 'Nombre total de recrutements dans la FP',
        'frequence':          'Annuelle',
    },
    'GT3PKI16': {
        'direction':          'DGFP',
        'groupe':             'GT3',
        'url':                '/kpi/gt3pki16',
        'intitule':           'Nombre de personnes handicapées recrutées dans la fonction  publique',
        'definition':         'Cet indicateur mesure le nombre absolu de personnes en situation de handicap ayant été recrutées (intégrées par voie de concours, contrat ou mesure spécifique) au sein de la fonction publique au cours d\'une période donnée (généralement une année)',
        'objectif':           'Garantir l\'accès des personnes handicapées à l\'emploi public, sans discrimination ; Mesurer la volonté effective de l\'État à intégrer cette catégorie vulnérable dans ses effectifs',
        'mode_calcul':        '∑Personnes handicapéess recrutées dans la fonction publique',
        'source':             'Fichiers de recrutement mentionnant le statut de handicap des agents; Registre centralisé des agents de l\'État permettant d\'identifier les personnes handicapées',
        'unite':              'nombre',
        'formule_type':       'nombre',
        'numerateur_label':   '',
        'denominateur_label': '',
        'frequence':          'Annuelle',
    },
    'GT3PKI17': {
        'direction':          'DGFP',
        'groupe':             'GT3',
        'url':                '/kpi/gt3pki17',
        'intitule':           'Taux d\'encadrement global dans la fonction publique',
        'definition':         'Rapport entre le nombre d\'agents d\'encadrement d\'une catégorie hiérarchique donnée (A, B ou C) et le nombre total d\'agents de la Fonction Publique',
        'objectif':           'Mesure la structure de la pyramide hiérarchique de l\'État',
        'mode_calcul':        '(Nombre de cadres de catégorie A / Effectif total) x 100',
        'source':             'Direction Générale de la Fonction Publique (DGFP) — fichier statistique des effectifs par catégorie Système d\'Information de Gestion des Ressources Humaines (SIGRH) — module effectifs Rapport annuel sur la situation des agents de l\'État (MTFP/DGRH) Annuaire statistique de la Fonction Publique',
        'unite':              '%',
        'formule_type':       'pourcentage',
        'numerateur_label':   'Agents de catégorie A et B (cadres)',
        'denominateur_label': 'Effectif total de la Fonction Publique',
        'frequence':          'Annuelle',
    },
    'GT3PKI18': {
        'direction':          'DGFP',
        'groupe':             'GT3',
        'url':                '/kpi/gt3pki18',
        'intitule':           'Taux de couverture des postes de responsabilité',
        'definition':         'Mesure la proportion de postes de responsabilité (direction, encadrement,décision) effectivement pourvus par rapport au nombre total de postes prévus',
        'objectif':           'Mesure la réactivité du MTFP dans la nomination des cadres; évaluer le niveau de remplissage des postes clés; identifier les vacances de postes',
        'mode_calcul':        '(Nombre de postes de responsabilité pourvus / Nombre total de postes prévus à l\'organigramme) x 100',
        'source':             'Organigrammes officiels; fichiers du personnel /base RH; décisions de nomination; rapport de gestion des effectifs',
        'unite':              '%',
        'formule_type':       'pourcentage',
        'numerateur_label':   'Postes de responsabilité pourvus',
        'denominateur_label': 'Nombre total de postes de responsabilite identifies',
        'frequence':          'Annuelle',
    },
    'GT3PKI19': {
        'direction':          'DGFP',
        'groupe':             'GT3',
        'url':                '/kpi/gt3pki19',
        'intitule':           'Indice de parité aux postes de décision',
        'definition':         'Mesure le niveau d\'équilibre entre hommes et femmes dans les postes de décision',
        'objectif':           'Mesure le \"plafond de verre\" dans l\'administration béninoise; promouvoir l\'égalité du genre; suivre la représentativité des femmes dans les sphères décisionnelles',
        'mode_calcul':        'Nombre de femmes occupant des postes de décision / Nombre d\'hommes occupant ces postes',
        'source':             'Actes de nomination ; rapport genre/ égalité; base de données RH',
        'unite':              'ratio',
        'formule_type':       'indice',
        'numerateur_label':   'Nombre de femmes occupant des postes de décision',
        'denominateur_label': 'Nombre total de postes de decision',
        'frequence':          'Annuelle',
    },
    'GT3PKI20': {
        'direction':          'DGFP',
        'groupe':             'GT3',
        'url':                '/kpi/gt3pki20',
        'intitule':           'Écart de promotion homme-femme',
        'definition':         'Mesure la différence entre le taux de promotion des hommes et celui des femmes sur une période donnée',
        'objectif':           'Détecte d\'éventuelles discriminations dans le déroulement de carrière ; promouvoir une équité dans les promotions',
        'mode_calcul':        'Ecart de promotion = Taux de promotion des femmes - Taux de promotion des hommes avec  Taux de promotion = (Nombre d\'agents promus / Nombre total du groupe) x 100',
        'source':             'Fichiers RH ; Listes de promotion / avancement ; Décisions administratives ; rapport de gestion du personnel',
        'unite':              'points de %',
        'formule_type':       'indice',
        'numerateur_label':   'Taux promotion femmes – Taux promotion hommes',
        'denominateur_label': '',
        'frequence':          'Annuelle',
    },
    'GT3PKI21': {
        'direction':          'DGFP',
        'groupe':             'GT3',
        'url':                '/kpi/gt3pki21',
        'intitule':           'Taux de féminisation des corps techniques',
        'definition':         'Mesure la proportion de femmes dans les corps techniques (ingénieurs, techniciens, etc. )',
        'objectif':           'Mesure à quel point la fonction publique devient un espace de \"choix ouvert\" où le genre ne dicte plus la trajectoire professionnelle,',
        'mode_calcul':        'Taux de féminisation = (Nombre de femmes dans les corps techniques / Effectif total des corps techniques) x 100',
        'source':             'Base de données RH ; repertoire des corps et métiers ; statistique du personnel',
        'unite':              '%',
        'formule_type':       'pourcentage',
        'numerateur_label':   'Femmes dans les corps techniques',
        'denominateur_label': 'Nombre total d\'agents dans les corps techniques',
        'frequence':          'Annuelle',
    },
}

DIRECTION_LABELS = {
    'SGM':  'Secretariat General du Ministere',
    'DSI':  'Direction des Systemes d\'Information',
    'DPAF': 'Direction de la Programmation et de l\'Administration Financiere',
    'DGT':  'Direction Generale du Travail',
    'DGFP': 'Direction Generale de la Fonction Publique',
    'IGSEP': 'Inspection Générale du Service d\'Exploitation et du Personnel',
}

DIRECTION_KPIS: dict = {}
for _code, _meta in KPI_META.items():
    DIRECTION_KPIS.setdefault(_meta['direction'], []).append(_code)

KPI_ORDRE_CHRONOLOGIQUE = [
    'GT1PKI01',
    'GT1PKI02',
    'GT1PKI03',
    'GT1PKI04',
    'GT1PKI05',
    'GT1PKI06',
    'GT1PKI07',
    'GT1PKI08',
    'GT1PKI09',
    'GT1PKI10',
    'GT1PKI11',
    'GT1PKI12',
    'GT1PKI13',
    'GT1PKI14',
    'GT1PKI15',
    'GT2PKI01',
    'GT2PKI02',
    'GT2PKI04',
    'GT2PKI05',
    'GT2PKI06',
    'GT2PKI07',
    'GT2PKI08',
    'GT2PKI09',
    'GT2PKI10',
    'GT3PKI01',
    'GT3PKI02',
    'GT3PKI03',
    'GT3PKI04',
    'GT3PKI05',
    'GT3PKI06',
    'GT3PKI07',
    'GT3PKI08',
    'GT3PKI09',
    'GT3PKI10',
    'GT3PKI11',
    'GT3PKI12',
    'GT3PKI13',
    'GT3PKI14',
    'GT3PKI15',
    'GT3PKI16',
    'GT3PKI17',
    'GT3PKI18',
    'GT3PKI19',
    'GT3PKI20',
    'GT3PKI21',
]


def prochain_code(groupe: str) -> str:
    """Prochain code libre dans un groupe en respectant la chronologie."""
    prefix = groupe.upper() + 'PKI'
    existing = [c for c in KPI_META if c.startswith(prefix)]
    if not existing:
        return prefix + '01'
    nums = []
    for c in existing:
        try: nums.append(int(c.replace(prefix, '')))
        except: pass
    return prefix + f'{max(nums)+1:02d}'


def get_kpis_pour_collecteur(structure_str: str) -> list:
    if not structure_str: return []
    dirs = [d.strip().upper() for d in structure_str.split(',') if d.strip()]
    seen, codes = set(), []
    for d in dirs:
        for c in DIRECTION_KPIS.get(d, []):
            if c not in seen:
                seen.add(c); codes.append(c)
    return codes


def get_direction_du_kpi(kpi_code: str) -> str:
    return KPI_META.get(kpi_code.upper(), {}).get('direction', '')


def get_label_direction(code: str) -> str:
    return DIRECTION_LABELS.get(code.upper(), code)